"""Initial revision

Revision ID: f0d93f9ad530
Revises: 
Create Date: 2025-04-28 01:12:15.024571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d93f9ad530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels_metadata',
    sa.Column('id_channel', sa.String(length=255), nullable=False),
    sa.Column('title_channel', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('description_channel', sa.Text(), nullable=True),
    sa.Column('view_count_channel', sa.BigInteger(), nullable=False),
    sa.Column('subscription_count', sa.BigInteger(), nullable=False),
    sa.Column('video_count', sa.BigInteger(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('account_creation_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_channel')
    )
    op.create_table('videos_metadata',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Text(), nullable=False),
    sa.Column('comment_count', sa.String(length=10), nullable=False),
    sa.Column('like_count', sa.Text(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels_metadata.id_channel'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_videos_metadata_channel_id'), 'videos_metadata', ['channel_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('comment_publish_date', sa.DateTime(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(length=255), nullable=True),
    sa.Column('commenter_channel_id', sa.String(length=255), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos_metadata.video_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_commenter_channel_id'), 'comments', ['commenter_channel_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_commenter_channel_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_videos_metadata_channel_id'), table_name='videos_metadata')
    op.drop_table('videos_metadata')
    op.drop_table('channels_metadata')
    # ### end Alembic commands ###
